name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: bahmutov/npm-install@v1
    - name: Build
      env:
        ASTRO_SITE: https://uki00a.github.io/blog/
        TRACKING_ID: G-R8RKYMTR71
      run: |
        yarn build
    - name: Post build # TODO: Workaround for the problem of not being able to fetch files in the _astro directory
      run: |
        mkdir dist/blog
        mv dist/*.css dist/blog
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
